FORMAT: 1A
HOST: http://bluntapi.herokuapp.com

# blunt_api

This API is consumed by blunt, a social application where users can meet new people over casual games.

## Users [/users]

### Get a User [GET /users/{id}]

returns a single user

+ Parameter

    + id: '1' - The ID of the user
    
+ Request    

    + Headers
    
            Authorization: token
        

+ Response 200 (application/json)
    + Attributes
        + User(User)

### Facebook Login [POST /users/facebook/login]

This end point is a part of the OAuth 2.0 workflow for facebook login / authorization

+ Request (application/json)

    + Headers
    
            Authorization: token
    
    + Attributes
    
        + Facebook(Facebook)

        
+ Response 200 (application/json)
    + Attributes
        + User(User)
        
### Filtered Users [POST /filteredusers]

This end point is used to return users based on search restrictions

+ Request (application/json)

    + Headers
    
            Authorization: token
    
    + Attributes
        + User(FilteredUsers)
            + Seekingprofile(Seekingprofile)
    
        

        
+ Response 200 (application/json)
    + Attributes
        + users (array[User])
        
            
# Data Structures

## User(object)
- id: 1 (number) - The ID of the user
- email: test@gmail.com (string) - The email of the user
- auth_token: xxxx123 (string) - The authentication token of the user
- facebook_id: 1 (number) - The facebook ID of the user, retrieved from facebook
- name: Bam Bam (string) - The name of user, retrieved from facebook
- provider: facebook (string) - The provider of the user information
- longitude: 1.001321 (number) - The longitude of the user
- latitude: 2.001323 (number) - The latitude of the user

## FilteredUsers(object)
- longitude: 1.001321 (number) - The longitude of the user
- latitude: 2.001323 (number) - The latitude of the user

## Facebook(object)
- token: xxx123 (string) - The facebook access token of the user

## Seekingprofile(object)
- minSeekDistance: 123.123456 (number) - The minimum distance another user is located
- maxSeekDistance: 123.123456 (number) - The maximum distance another user is located